camera:
  source: '/dev/video0'   # กล้อง webcam หรือ RTSP
  width: 640
  height: 480
  frame_rate: 25
  flip_frame: FALSE     # กลับภาพซ้าย-ขวาเหมือนกระจก กรณีใช้กล้อง build-in ของโน๊ตบุ๊ค

yolo:
  model: "yolov8n.pt"
  conf: 0.5          # ค่า confidence threshold (0–1)
  iou: 0.45          # ค่า IoU threshold สำหรับ NMS
  classes: [0, 3]       # ตรวจจับตรม COCO class id  # 0=person, 2=bicycle ,3=car ,4=motorcycle ,6=bus ,8=truck

# --- โซนสำหรับ cross pixel (หน่วย % ของความกว้าง frame) ---
zones:
  zone_a: 70         # ขวา → เกณฑ์ pixel = frame_width * 70%
  zone_b: 30         # ซ้าย → เกณฑ์ pixel = frame_width * 30%

counter:
  cooldown: 0.5        # วินาที กันนับซ้ำ